---
acc_cluster:
  - Name: stencil2d_clstr
  - DMA:
    - Name: dma
      MaxReqSize: 64
      BufferSize: 128
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - Accelerator:
    - Name: Top
      IrPath: benchmarks/sys_validation/stencil2d/hw/top.ll
      ConfigPath: benchmarks/sys_validation/stencil2d/hw/top.ini
      PIOSize: 25
      InterruptNum: 68
      PIOMaster: LocalBus
      # Local to PIO
      LocalSlaves: LocalBus
      Debug: False
  - Accelerator:
    - Name: stencil2d
      IrPath: benchmarks/sys_validation/stencil2d/hw/stencil2d.ll
      ConfigPath: benchmarks/sys_validation/stencil2d/hw/stencil2d.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: ORIG
        Type: SPM
        Size: 32768
        Ports: 2
    - Var:
      - Name: SOL
        Type: SPM
        Size: 32768
        Ports: 2
    - Var:
      - Name: FILTER
        Type: SPM
        Size: 36
        Ports: 2