---
acc_cluster:
  - Name: lenet5_clstr
  - DMA:
    - Name: dma
      BufferSize: 128
      MaxReqSize: 64
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - DMA:
    - Name: StreamDma
      PIOMaster: LocalBus
      Size: 8
      Type: Stream
      ReadInt: 210
      WriteInt: 211
      BufferSize: 128
  - Accelerator:
    - Name: top
      IrPath: benchmarks/lenet5/stream/hw/ir/top.ll
      ConfigPath: benchmarks/lenet5/stream/hw/configs/top.ini
      PIOSize: 9
      PIOMaster: LocalBus
      LocalSlaves: LocalBus
      Debug: False
      InterruptNum: 68
  - Accelerator:
    - Name: conv0
      IrPath: benchmarks/lenet5/stream/hw/ir/conv0.ll
      ConfigPath: benchmarks/lenet5/stream/hw/configs/conv0.ini
      Debug: True
      PIOSize: 1
      PIOMaster: LocalBus
      StreamOut: StreamDma
    - Var:
      - Name: Conv0LineBuff
        Type: SPM
        Size: 640
        Ports: 25
    - Var:
      - Name: Conv0Weights
        Type: SPM
        Size: 600
        Ports: 25
    # - Var:
    #   - Name: Conv0Window
    #     Type: SPM
    #     Size: 100
    #     Ports: 25
        # ReadyMode: True
        # ResetOnRead: True
        # WriteOnValid: False
    - Var:
      - Name: Conv0Out
        Type: Stream
        StreamSize: 4
        BufferSize: 64
        InCon: conv0
        OutCon: pool0
  - Accelerator:
    - Name: pool0
      IrPath: benchmarks/lenet5/stream/hw/ir/pool0.ll
      ConfigPath: benchmarks/lenet5/stream/hw/configs/pool0.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Pool0Window
        Type: SPM
        Size: 1344
        Ports: 4
        ReadyMode: True
        ResetOnRead: True
        WriteOnValid: False
    - Var:
      - Name: Pool0Out
        Type: Stream
        StreamSize: 4
        BufferSize: 64
        InCon: pool0
        OutCon: conv1
  - Accelerator:
    - Name: conv1
      IrPath: benchmarks/lenet5/stream/hw/ir/conv1.ll
      ConfigPath: benchmarks/lenet5/stream/hw/configs/conv1.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Conv1LineBuff
        Type: SPM
        Size: 4704
        Ports: 150
    - Var:
      - Name: Conv1Weights
        Type: SPM
        Size: 9600
        Ports: 150
    # - Var:
    #   - Name: Conv1Window
    #     Type: SPM
    #     Size: 600
    #     Ports: 150
    #     ReadyMode: True
    #     ResetOnRead: True
    #     WriteOnValid: False
    - Var:
      - Name: Conv1Out
        Type: Stream
        StreamSize: 4
        BufferSize: 64
        InCon: conv1
        OutCon: pool1
  - Accelerator:
    - Name: pool1
      IrPath: benchmarks/lenet5/stream/hw/ir/pool1.ll
      ConfigPath: benchmarks/lenet5/stream/hw/configs/pool1.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Pool1Window
        Type: SPM
        Size: 1280
        Ports: 4
        ReadyMode: True
        ResetOnRead: True
        WriteOnValid: False
    - Var:
      - Name: Pool1Out
        Type: Stream
        StreamSize: 4
        BufferSize: 64
        InCon: pool1
        OutCon: conv2
  - Accelerator:
    - Name: conv2
      IrPath: benchmarks/lenet5/stream/hw/ir/conv2.ll
      ConfigPath: benchmarks/lenet5/stream/hw/configs/conv2.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Conv2Weights
        Type: SPM
        Size: 192000
        Ports: 400
    - Var:
      - Name: Conv2LineBuff
        Type: SPM
        Size: 1600
        Ports: 400
        ReadyMode: True
        ResetOnRead: False
    - Var:
      - Name: Conv2Out
        Type: Stream
        StreamSize: 4
        BufferSize: 64
        InCon: conv2
        OutCon: fc0
  - Accelerator:
    - Name: fc0
      IrPath: benchmarks/lenet5/stream/hw/ir/fc0.ll
      ConfigPath: benchmarks/lenet5/stream/hw/configs/fc0.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
      StreamIn: StreamDma
    - Var:
      - Name: FC0Weights
        Type: SPM
        Size: 40320
        Ports: 120
    - Var:
      - Name: FC0LineBuff
        Type: SPM
        Size: 480
        Ports: 120
        ReadyMode: True
        ResetOnRead: False