---
acc_cluster:
  - Name: bfs_clstr
  - DMA:
    - Name: dma
      MaxReqSize: 64
      BufferSize: 128
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - Accelerator:
    - Name: Top
      IrPath: benchmarks/sys_validation/bfs/hw/top.ll
      ConfigPath: benchmarks/sys_validation/bfs/hw/top.ini
      PIOSize: 37
      InterruptNum: 68
      PIOMaster: LocalBus
      # Local to PIO
      LocalSlaves: LocalBus
      Debug: False
  - Accelerator:
    - Name: bfs
      IrPath: benchmarks/sys_validation/bfs/hw/bfs.ll
      ConfigPath: benchmarks/sys_validation/bfs/hw/bfs.ini
      Debug: False
      PIOSize: 5
      PIOMaster: LocalBus
    - Var:
      - Name: NODES
        Type: SPM
        Size: 2048
        Ports: 1
    - Var:
      - Name: EDGES
        Type: SPM
        Size: 16384
        Ports: 1
    - Var:
      - Name: LEVELS
        Type: SPM
        Size: 256
        Ports: 1
    - Var:
      - Name: LEVELCOUNTS
        Type: SPM
        Size: 40
        Ports: 1